# Travis Configuration
sudo: false
language: objective-c
os: osx
compiler:
  - clang
  - gcc

# Install Dependencies
before_script:
  - if [ "$CXX" = "g++" ]; then export CXX=g++-4.8; fi
  - brew update
  - brew outdated cmake || brew upgrade cmake
  - brew install python
  - pip install cpp-coveralls

# Run the Test Script
script:
  - cd build
  - cmake ..
  - cmake --build .

  # Test the Core Binaries
  - ./clinfo > /dev/null
  - ./chlorine > /dev/null

  # Test the Mandelbrot Example
  - make mandelbrot
  - cd examples/mandelbrot
  - ./mandelbrot > /dev/null
  - cd -

  # Test the Swap Example
  - make swap
  - cd examples/swap
  - ./swap > /dev/null
  - cd -

  # Run the Test Suite
  - make check

# Upload Code Coverage Data
after_success:
  - coveralls --root .. --exclude chlorine/include/cl.hpp  --exclude chlorine/clinfo/clinfo.cpp --exclude tests

# Display Compiler Information
after_script:
  - $CXX --version
